### ISSUE TITLE
cutting off some of the text when making responses

### ISSUE THREAD

**Issue by JonLittleIT** [bcExpt1123/chatgpt-example#2]
I noticed while testing that some of the promps are coming back cut off and the length of the response is limited to so many characters and its not sending the entire response back to the front end.

**Comment by bcExpt1123** [comment]
@JonLittleIT 
Thanks for your report.

Could you add screenshots?

**Comment by JonLittleIT** [comment]
use this for testing. "please explain how to build a start up with a budget of 10,000 and give me top 20 steps to follow." 
<img width="917" alt="image" src="https://user-images.githubusercontent.com/22354862/236877773-33a2a5a1-0930-4dca-b0b3-5407ca59bd15.png">

**Comment by bcExpt1123** [comment]
@JonLittleIT 
Thank you for your detailed description.
And sorry for deplyed answer.

I solved the issue.

https://github.com/bcExpt1123/chatgpt-example/blob/8be8c04dbd3b9406ef354e86ba35321e0d5d07a4/backend/index.js#L22
